baseURL = "/"
languageCode = "en-us"
title = "Shoultz WIKI"
theme = "learn"
buildDrafts = true
enableEmojie = true
enableInlineShortcodes = true

[params]
    description = "Documentation"
    author = "Kevin Shoultz"
    showVisitedLinks = false
    disableBreadcrumb = false
    disableNextPrev = false
    themeVariant = "gravitywell"
    shortcutTitle = "More"
    extVersion = "7.1.0"

[outputs]
    home = [ "HTML", "RSS", "JSON" ]

[markup]
    [markup.goldmark]
        [markup.golmark.renderer]
            unsafe = true

[[menu.shortcuts]]
    name = "Shoultz Interactive" 
    url = "http://www.shoultzinteractive.com"

[[menu.shortcuts]]
    name = "THe Gravitywell Project" 
    url = "http://www.thegravitywell.com/"

[[menu.shortcuts]]
    name = "Maps Test Harness" 
    url = "http://maps-test-harness.herokuapp.com/"

[[menu.shortcuts]]
    name = "Charts Test Harness" 
    url = "http://charts-test-harness.herokuapp.com/"